name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    env:
      GLFW_TAG: 3.3-stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare vendor (all OS)
        shell: bash
        run: |
          set -e
          mkdir -p vendor
          if grep -q 'GLFW_TAG' vendor/prepare.sh 2>/dev/null; then
            GLFW_TAG="${GLFW_TAG}" bash vendor/prepare.sh
          else
            if [ ! -d vendor/glfw ]; then
              git clone --depth 1 --branch "${GLFW_TAG}" https://github.com/glfw/glfw.git vendor/glfw
            fi
          fi
          test -d vendor/glfw

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install deps (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xorg-dev libx11-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev libgl1-mesa-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: brew install glfw

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -- -j

      - name: Test
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure
