name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      # Dependencies
      - name: Install deps (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libgl1-mesa-dev xorg-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install glfw

      - name: Setup vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-vcpkg@v1
        with:
          vcpkg-triplet: x64-windows

      - name: Install deps (Windows via vcpkg)
        if: runner.os == 'Windows'
        run: vcpkg install glfw3

      # Configure
      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: >
          cmake -S . -B build
          -A x64
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake

      # Build
      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --build build --config ${{ matrix.build_type }} -- -j

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build --config ${{ matrix.build_type }}

      # Test
      - name: Test (Linux/macOS)
        if: runner.os != 'Windows'
        run: ctest --test-dir build --output-on-failure

      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure
